#@+leo
#@+node:0::@file easy/Makefile
#@+body
all:
	rm -rf doc/detail
	epydoc \
		   -o doc/detail \
		   --show-imports \
		   -n "exPyCrypto - World's Easiest Crypto for Python" \
		   ezPyCrypto.py

clean:
	rm -rf *~ *.pyc ex_* doc/*.tar.gz build

#@-body
#@-node:0::@file easy/Makefile
#@-leo
